### ISSUE TITLE
Always skipping PRs (maybe better to webhook on status messages?)

### ISSUE THREAD

**Issue by nkbt** [kkemple/greenkeeper-keeper#27] opened 2016-09-29 01:38 UTC
Greenkeeper keeps updating PRs, se each PR has bunch of other actions and statuses rather then "opened".

I think it might have sense to listen to `"status": "success"` messages instead of `"action":"opened"`

Here is an example of such message:

``` json
{
  "id": 776564107,
  "sha": "3675455eaa66debf97025913d8c3ff2fae16f30b",
  "name": "nkbt/react-component-template",
  "target_url": "https://ci.appveyor.com/project/nkbt/react-component-template/build/763",
  "context": "continuous-integration/appveyor/pr",
  "description": "AppVeyor build succeeded",
  "state": "success",
  "commit": {
    "sha": "3675455eaa66debf97025913d8c3ff2fae16f30b",
    "commit": {
      "author": {
        "name": "greenkeeperio-bot",
        "email": "support@greenkeeper.io",
        "date": "2016-09-29T01:17:38Z"
      },
      "committer": {
        "name": "greenkeeperio-bot",
        "email": "support@greenkeeper.io",
        "date": "2016-09-29T01:17:38Z"
      },
      "message": "chore(package): update babel-cli to version 6.16.0\n\nhttps://greenkeeper.io/",
      "tree": {
        "sha": "660dd68e3b9a08fa9e406e12dbe020d8b3e2a7d6",
        "url": "https://api.github.com/repos/nkbt/react-component-template/git/trees/660dd68e3b9a08fa9e406e12dbe020d8b3e2a7d6"
      },
      "url": "https://api.github.com/repos/nkbt/react-component-template/git/commits/3675455eaa66debf97025913d8c3ff2fae16f30b",
      "comment_count": 0
    },
    "url": "https://api.github.com/repos/nkbt/react-component-template/commits/3675455eaa66debf97025913d8c3ff2fae16f30b",
    "html_url": "https://github.com/nkbt/react-component-template/commit/3675455eaa66debf97025913d8c3ff2fae16f30b",
    "comments_url": "https://api.github.com/repos/nkbt/react-component-template/commits/3675455eaa66debf97025913d8c3ff2fae16f30b/comments",
    "author": {
      "login": "greenkeeperio-bot",
      "id": 14790466,
      "avatar_url": "https://avatars.githubusercontent.com/u/14790466?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/greenkeeperio-bot",
      "html_url": "https://github.com/greenkeeperio-bot",
      "followers_url": "https://api.github.com/users/greenkeeperio-bot/followers",
      "following_url": "https://api.github.com/users/greenkeeperio-bot/following{/other_user}",
      "gists_url": "https://api.github.com/users/greenkeeperio-bot/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/greenkeeperio-bot/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/greenkeeperio-bot/subscriptions",
      "organizations_url": "https://api.github.com/users/greenkeeperio-bot/orgs",
      "repos_url": "https://api.github.com/users/greenkeeperio-bot/repos",
      "events_url": "https://api.github.com/users/greenkeeperio-bot/events{/privacy}",
      "received_events_url": "https://api.github.com/users/greenkeeperio-bot/received_events",
      "type": "User",
      "site_admin": false
    },
    "committer": {
      "login": "greenkeeperio-bot",
      "id": 14790466,
      "avatar_url": "https://avatars.githubusercontent.com/u/14790466?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/greenkeeperio-bot",
      "html_url": "https://github.com/greenkeeperio-bot",
      "followers_url": "https://api.github.com/users/greenkeeperio-bot/followers",
      "following_url": "https://api.github.com/users/greenkeeperio-bot/following{/other_user}",
      "gists_url": "https://api.github.com/users/greenkeeperio-bot/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/greenkeeperio-bot/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/greenkeeperio-bot/subscriptions",
      "organizations_url": "https://api.github.com/users/greenkeeperio-bot/orgs",
      "repos_url": "https://api.github.com/users/greenkeeperio-bot/repos",
      "events_url": "https://api.github.com/users/greenkeeperio-bot/events{/privacy}",
      "received_events_url": "https://api.github.com/users/greenkeeperio-bot/received_events",
      "type": "User",
      "site_admin": false
    },
    "parents": [
      {
        "sha": "a98557cde0886216b593a8b54392d2f41387ac27",
        "url": "https://api.github.com/repos/nkbt/react-component-template/commits/a98557cde0886216b593a8b54392d2f41387ac27",
        "html_url": "https://github.com/nkbt/react-component-template/commit/a98557cde0886216b593a8b54392d2f41387ac27"
      }
    ]
  },
  "branches": [
    {
      "name": "greenkeeper-babel-cli-6.16.0",
      "commit": {
        "sha": "3675455eaa66debf97025913d8c3ff2fae16f30b",
        "url": "https://api.github.com/repos/nkbt/react-component-template/commits/3675455eaa66debf97025913d8c3ff2fae16f30b"
      }
    }
  ],
  "created_at": "2016-09-29T01:27:40Z",
  "updated_at": "2016-09-29T01:27:40Z",
  "repository": {
    "id": 38535680,
    "name": "react-component-template",
    "full_name": "nkbt/react-component-template",
    "owner": {
      "login": "nkbt",
      "id": 175264,
      "avatar_url": "https://avatars.githubusercontent.com/u/175264?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/nkbt",
      "html_url": "https://github.com/nkbt",
      "followers_url": "https://api.github.com/users/nkbt/followers",
      "following_url": "https://api.github.com/users/nkbt/following{/other_user}",
      "gists_url": "https://api.github.com/users/nkbt/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/nkbt/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/nkbt/subscriptions",
      "organizations_url": "https://api.github.com/users/nkbt/orgs",
      "repos_url": "https://api.github.com/users/nkbt/repos",
      "events_url": "https://api.github.com/users/nkbt/events{/privacy}",
      "received_events_url": "https://api.github.com/users/nkbt/received_events",
      "type": "User",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/nkbt/react-component-template",
    "description": "Base for React Components",
    "fork": false,
    "url": "https://api.github.com/repos/nkbt/react-component-template",
    "forks_url": "https://api.github.com/repos/nkbt/react-component-template/forks",
    "keys_url": "https://api.github.com/repos/nkbt/react-component-template/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/nkbt/react-component-template/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/nkbt/react-component-template/teams",
    "hooks_url": "https://api.github.com/repos/nkbt/react-component-template/hooks",
    "issue_events_url": "https://api.github.com/repos/nkbt/react-component-template/issues/events{/number}",
    "events_url": "https://api.github.com/repos/nkbt/react-component-template/events",
    "assignees_url": "https://api.github.com/repos/nkbt/react-component-template/assignees{/user}",
    "branches_url": "https://api.github.com/repos/nkbt/react-component-template/branches{/branch}",
    "tags_url": "https://api.github.com/repos/nkbt/react-component-template/tags",
    "blobs_url": "https://api.github.com/repos/nkbt/react-component-template/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/nkbt/react-component-template/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/nkbt/react-component-template/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/nkbt/react-component-template/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/nkbt/react-component-template/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/nkbt/react-component-template/languages",
    "stargazers_url": "https://api.github.com/repos/nkbt/react-component-template/stargazers",
    "contributors_url": "https://api.github.com/repos/nkbt/react-component-template/contributors",
    "subscribers_url": "https://api.github.com/repos/nkbt/react-component-template/subscribers",
    "subscription_url": "https://api.github.com/repos/nkbt/react-component-template/subscription",
    "commits_url": "https://api.github.com/repos/nkbt/react-component-template/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/nkbt/react-component-template/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/nkbt/react-component-template/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/nkbt/react-component-template/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/nkbt/react-component-template/contents/{+path}",
    "compare_url": "https://api.github.com/repos/nkbt/react-component-template/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/nkbt/react-component-template/merges",
    "archive_url": "https://api.github.com/repos/nkbt/react-component-template/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/nkbt/react-component-template/downloads",
    "issues_url": "https://api.github.com/repos/nkbt/react-component-template/issues{/number}",
    "pulls_url": "https://api.github.com/repos/nkbt/react-component-template/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/nkbt/react-component-template/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/nkbt/react-component-template/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/nkbt/react-component-template/labels{/name}",
    "releases_url": "https://api.github.com/repos/nkbt/react-component-template/releases{/id}",
    "deployments_url": "https://api.github.com/repos/nkbt/react-component-template/deployments",
    "created_at": "2015-07-04T14:02:41Z",
    "updated_at": "2016-09-26T22:18:40Z",
    "pushed_at": "2016-09-29T01:22:01Z",
    "git_url": "git://github.com/nkbt/react-component-template.git",
    "ssh_url": "git@github.com:nkbt/react-component-template.git",
    "clone_url": "https://github.com/nkbt/react-component-template.git",
    "svn_url": "https://github.com/nkbt/react-component-template",
    "homepage": null,
    "size": 673,
    "stargazers_count": 45,
    "watchers_count": 45,
    "language": "JavaScript",
    "has_issues": true,
    "has_downloads": true,
    "has_wiki": false,
    "has_pages": true,
    "forks_count": 6,
    "mirror_url": null,
    "open_issues_count": 12,
    "forks": 6,
    "open_issues": 12,
    "watchers": 45,
    "default_branch": "master"
  },
  "sender": {
    "login": "nkbt",
    "id": 175264,
    "avatar_url": "https://avatars.githubusercontent.com/u/175264?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/nkbt",
    "html_url": "https://github.com/nkbt",
    "followers_url": "https://api.github.com/users/nkbt/followers",
    "following_url": "https://api.github.com/users/nkbt/following{/other_user}",
    "gists_url": "https://api.github.com/users/nkbt/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/nkbt/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/nkbt/subscriptions",
    "organizations_url": "https://api.github.com/users/nkbt/orgs",
    "repos_url": "https://api.github.com/users/nkbt/repos",
    "events_url": "https://api.github.com/users/nkbt/events{/privacy}",
    "received_events_url": "https://api.github.com/users/nkbt/received_events",
    "type": "User",
    "site_admin": false
  }
}
```

There might be several messages like that, so you will still need to make a call to see if all checks are passed.

Feel free to close if out of scope.

I will fork and give it a shot bit later, when I have some time

Cheers!

**Comment by kkemple** [comment] 2016-12-05 19:31
is this a duplicate of #29 ?

**Comment by nkbt** [comment] 2016-12-05 22:30
Not exactly, I feel like they are a bit different in nature

**Comment by travi** [comment] 2017-01-08 21:23
closing this in favor of greenkeeper-keeper/hapi-greenkeeper-keeper#21

**Closed as completed by travi** 2017-01-08 21:23 UTC
